version: "3.7"

services:
  nginx:
    build: "./.docker/local/nginx"
    container_name: test-nginx
    ports:
      - "60:60"
    volumes:
      - ./laravel/public:/app/public
      - ./.docker/local/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  app:
    build: "./.docker/local/php"
    container_name: test-app
    working_dir: /app
    volumes:
      - "./laravel:/app"
      - "./.docker/local/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
    ports:
      - "9000:9000"
    depends_on:
      - mysql

  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - "./laravel/storage/mysql:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: skiller
      MYSQL_USER: skiller
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    container_name: test-mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_ARBITRARY: 1
      PMA_HOSTS: mysql
      PMA_USER: ${DB_USERNAME:-root}
      PMA_PASSWORD: ${DB_PASSWORD:-root}
    ports:
      - "9090:80"
